// generated by stringer -type=binop; DO NOT EDIT

package main

import "fmt"

const _binop_name = "binANDbinDIVbinLTbinEQbinGTbinSUBbinFDIVbinMULbinADDbinGEbinLEbinMODbinNEbinORbinArrayIndex"

var _binop_index = [...]uint8{0, 6, 12, 17, 22, 27, 33, 40, 46, 52, 57, 62, 68, 73, 78, 91}

func (i binop) String() string {
	if i+1 >= binop(len(_binop_index)) {
		return fmt.Sprintf("binop(%d)", i)
	}
	return _binop_name[_binop_index[i]:_binop_index[i+1]]
}
