// Code generated by "stringer -type=primitive"; DO NOT EDIT

package main

import "fmt"

const _primitive_name = "primIntprimBoolprimRealprimStringprimChar"

var _primitive_index = [...]uint8{0, 7, 15, 23, 33, 41}

func (i primitive) String() string {
	if i < 0 || i >= primitive(len(_primitive_index)-1) {
		return fmt.Sprintf("primitive(%d)", i)
	}
	return _primitive_name[_primitive_index[i]:_primitive_index[i+1]]
}
