// generated by stringer --type=Token; DO NOT EDIT

package main

import "fmt"

const _Token_name = "tInvalidtLiteraltANDtARRAYtASSIGNtBEGINtBOOLEANtBREAKtCHARtCONTINUEtDIVtDOtDOTDOTtDOWNTOtELSEtENDtFALSEtFNUMBERtFORtFUNCTIONtGEtGOTOtIDtIFtINTEGERtLEtMODtNEtNOTtNUMBERtOFtORtPROCEDUREtPROGRAMtQSTRINGtREALtRECORDtREPEATtSTRINGtTHENtTHIStTOtTRUEtTYPEtUNTILtVARtWHILE"

var _Token_index = [...]uint16{8, 16, 20, 26, 33, 39, 47, 53, 58, 67, 71, 74, 81, 88, 93, 97, 103, 111, 115, 124, 127, 132, 135, 138, 146, 149, 153, 156, 160, 167, 170, 173, 183, 191, 199, 204, 211, 218, 225, 230, 235, 238, 243, 248, 254, 258, 264}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)) {
		return fmt.Sprintf("Token(%d)", i)
	}
	hi := _Token_index[i]
	lo := hi * 0 // bug fix for https://github.com/golang/go/issues/9288
	if i > 0 {
		lo = _Token_index[i-1]
	}
	return _Token_name[lo:hi]
}
