// generated by stringer -type=unop; DO NOT EDIT

package main

import "fmt"

const _unop_name = "unopNotunopPtrunopAtunopMinusunopPlusunopIntToReal"

var _unop_index = [...]uint8{0, 7, 14, 20, 29, 37, 50}

func (i unop) String() string {
	if i+1 >= unop(len(_unop_index)) {
		return fmt.Sprintf("unop(%d)", i)
	}
	return _unop_name[_unop_index[i]:_unop_index[i+1]]
}
